### ISSUE TITLE
Add further updates to website design

### ISSUE THREAD

**Issue by ConorOkus** [lightningdevkit/lightningdevkit.org#49]
This is an issue is to help us track, improve and implement further visual aspects of the website. Most of what we need is there, but it's important to get the base/template as solid as possible as it will be used by the BDK project. We are looking to make updates in the following areas.

- [x] The title fonts seem to be randomly missing pixels, a rendering issue?
- [x] Remove the expanding sidebar as it's difficult to tell what is part of the current article and what links out to other pages. (Discussion needed)
- [x] Support for a blog page
- [ ] #58
- [x] #60

**Comment by thunderbiscuit** [comment]
First off that's some seriously good work @dennisreimann. I come from the bitcoindevkit side of things, and it's fair to say we're very interested in what you're building.

A few comments on my end:
1. The sidebar currently expends to show header tags from the selected articles. My main issue with this is that on long articles, your sidebar just grows really big and you can’t tell what’s a section of an article and what’s a link to a different article (the margins are not differentiating enough). It also feels like the sidebar is playing tricks on you: try for example to switch between articles and notice the sidebar jump up and down and grow and shrink to show/hide the headers of each given article you clicked on. The sidebar, for me, serves as a mental map of what is available/what I can read. I like it to be very stable across clicks.
2. Agree with @ConorOkus the font has odd "e" characters. I thought it was only on headers but it's actually throughout; once you're used to it it's not that bad, but it's a weird little quirk that distracts the eye IMO.

**Comment by dennisreimann** [comment]
Working on this in #50 now. 

@thunderbiscuit I've made it so that only the h1 and h2 headline levels show up in the sidebar. Does this work for you?
Also changed the font import, which seems to have resolved the issue for @ConorOkus. Can you confirm it works for you too?

Preview here: https://deploy-preview-50--ldk-docs-preview.netlify.app/

**Comment by thunderbiscuit** [comment]
Very nice. Those are solid additions IMO!

**Comment by ConorOkus** [comment]
I wonder if we even need the H2 headings in the sidebar. One of my favourite docs are https://nextjs.org/docs

Looking at the current state of the docs these H2's consist of a lot of content and could be separate pages IMO.

Thoughts @dennisreimann @thunderbiscuit

**Comment by dennisreimann** [comment]
@ConorOkus That'd basically mean we don't show headings/an outline of the current doc in the sidebar. I'm fine either way and don't have a strong preference here.

**Comment by thunderbiscuit** [comment]
I mean for me, the "inside" of a page/article belong to that page more than the sidebar, so in that sense yes I prefer none. But restricting to h2 helped remove the clutter quite a bit. The issue of whether they should be their own separate articles is maybe more something for LDK to see.

But note the font/type hierarchy here:
![image](https://user-images.githubusercontent.com/39974688/125110032-18372600-e0b2-11eb-9388-80faaefdd097.png)

The font weight/spacing/size differentiation is not that strong, and so I find it becomes muddy as to what is what when you have pieces of articles within the sidebar. Just my opinion.

**Comment by thunderbiscuit** [comment]
Something you see sometimes is a Table of Content at the top of long articles. This gives the eye a clear mapping for what's inside the article, without messing with the mental map for "what's on the website". Note also that once you click on a section of the article, it shows up with the header at the top, but can easily be mistaken for it's own page... Not that big of a deal, but is another reason why sections and articles don't mesh well.

![image](https://user-images.githubusercontent.com/39974688/125110452-94ca0480-e0b2-11eb-8666-0fecb2ef70f2.png)

The screenshot above could easily fool you into thinking you're on the "Managing Channels" page, but in fact your in the "Managing Channels" section of the "Using LDK" page.

**Comment by dennisreimann** [comment]
@thunderbiscuit Ok, pushed an update that gets rid of the headings in the sidebar. Thanks for elaborating these concerns. I got a better understanding of what you mean and now tend to agree.

If pages grow to complex we can easily split them up or add a table of contents.

**Comment by thunderbiscuit** [comment]
I love how you can push changes and the Netlify test site updates immediately. It's so intuitive to iterate upon. Sick work by the way. Another hit on your VuePress long list of hits.

**Comment by ConorOkus** [comment]
Yeah, I guess my argument is that we should keep the structure so you can get an overall feel for what's in the article but they should actually be separate pages and not sections in the article because it makes the pages unnecessarily long. I suspect having separate pages will be better for SEO and search as well.

**Comment by thunderbiscuit** [comment]
Good point @ConorOkus. If everything is in gigantic pages it's harder to find what you want. And SEO I don't know enough about, but it feels like indeed it would be better to have specialized pages.

**Comment by sbddesign** [comment]
@dennisreimann Looking really good!

One subtle detail, not high priority. Have you tried the left-side border-line like this?

Ideally the left/right borders line up with the center of the illustration grids.

![ldk-1](https://user-images.githubusercontent.com/2414177/126149762-848d2175-75e3-4168-bc4e-b5fe6f5a5bbf.png)

**Comment by dennisreimann** [comment]
@sbddesign We can fine tune that, it'd be the same as for the content container at the bottom …

![home](https://user-images.githubusercontent.com/886/126150253-21b123f7-3f28-4130-86f0-dc0675f8917b.png)

**Comment by sbddesign** [comment]
@dennisreimann The blog is looking good. I noticed something that looks like an error. The left nav seems to switch when clicking on a blog post. I feel like the the individual blog post should have the same sidebar as the blog archive.

![ldk-blog-1](https://user-images.githubusercontent.com/2414177/126150216-6e00b142-b13a-4806-ae7d-903dd815e419.png)

![ldk-blog-2](https://user-images.githubusercontent.com/2414177/126150218-12fb8477-5612-42dd-b0f9-0c44569f5499.png)

**Comment by dennisreimann** [comment]
@sbddesign Good catch, will update both things you mentioned with the next run of changes.

**Comment by sbddesign** [comment]
I'd suggest that we include a default image that is included in the OpenGraph metadata for each page. That way, the page shows up with a nice LDK branded picture when shared on social media.

_(Optionally, each page could have its own meta image. For example, one might conceivably want the ability to add an image to the top of the blog post above the header -- but that could all come later.)_

Specifically, for the immediate future, I am proposing having this PNG (or a PNG like this) included in the `<head>` section via `og:image` and `twitter:image` properties.

![LDK OG Meta Image](https://user-images.githubusercontent.com/2414177/126152094-7f798c5c-9cde-4269-8a60-26d2faee2666.png)

**Comment by sbddesign** [comment]
This is my mistake -- the grid backgrounds behind the images do not show up in dark mode. I have since found a simple solution for this in Figma that easily translates into SVG. When there is consensus on final color palette, I will make you sure I get this corrected artwork to you.

That is all I got right now, thanks for listening. 🙏

![ldk-dark-mode-grid-issue](https://user-images.githubusercontent.com/2414177/126152630-881ba854-4dee-4668-a450-4d3da8d83482.png)

**Comment by thunderbiscuit** [comment]
Blog looks rad. Good stuff. @notmandatory have you seen this? I think it would be a great fit for us as well.

**Comment by ConorOkus** [comment]
Look very slick, found a little bug when the page 404's. The sidebar seems to overlay the page. 

<img width="1437" alt="Screenshot 2021-07-19 at 13 23 48" src="https://user-images.githubusercontent.com/10757874/126208630-99477632-6582-48fa-89c7-c94491f82bdd.png">

**Comment by dennisreimann** [comment]
Addressed all points mentioned :)

@ConorOkus I've created a separate issue for the Algolia search (#58), because we need to have the Vuepress version live to apply for it. 

What is the state of the color scheme updates?

**Comment by ConorOkus** [comment]
Thanks for the updates. 

I'll chase the colour scheme up over slack, a few other components we need to change include the `Features` section on the landing page. Still need to identify what we want on there. I think a grid layout with each feature linking out to its own page in the docs could be the way to go but we discuss more in the slack. 

We also need to integrate a footer.

**Comment by dennisreimann** [comment]
@ConorOkus Ok, let's merge this general update PR and open/use separate issues to track the other things individually.
