### ISSUE TITLE
Vuepress: Change the colour scheme

### ISSUE THREAD

**Issue by dennisreimann** [lightningdevkit/lightningdevkit.org#60]
Remove the blue/purple as it's similar to what Square Crypto and Lightning Labs use. 
Let's experiment with the green the current site is using or some other alternative.

**Comment by sbddesign** [comment]
## Color Scheme Variations
- [Current Color Scheme](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=301%3A13429)
- [Green Color Scheme](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=507%3A15876)
- [Blue-Green Color Scheme](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=507%3A16596)
- [Orange Color Scheme](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=547%3A16144)

**Comment by ConorOkus** [comment]
I'm in favour of Blue-Green, could be persuaded to go Green though.

**Comment by dennisreimann** [comment]
I like the Blue Green one too. Have you tried Blue Yellow too?

**Comment by sbddesign** [comment]
> I like the Blue Green one too. Have you tried Blue Yellow too?

@dennisreimann Here is a[quick mockup of Blue and Yellow](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=570%3A16408).

That's just to get a general sense, I would need to tweak some details there.

**Comment by dennisreimann** [comment]
Hey @sbddesign, it also looks good and I like it better than the blue/orange one – it also fits the Lightning theme better imho. I'd vote for the new blue/yellow one and blue/green as fallback. Good job with all those variations!

**Comment by ConorOkus** [comment]
Ship it!

**Comment by dennisreimann** [comment]
> Ship it!

Which one? :D

**Comment by ConorOkus** [comment]
Blue/Yellow.

@moneyball @GBKS any thoughts?

**Comment by dennisreimann** [comment]
@sbddesign Can you let me know when the blue/yellow theme changes are finalized in Figma?

**Comment by sbddesign** [comment]
@dennisreimann The illustrations are ready. They are setup as component variations and have SVG exports defined in Figma. They are at the bottom of this ["Brand Assets" artboard](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=604%3A17117).

Here is a brief video where I walk through what I have been doing with the color palette change. There has been 2 conversations running about this, one here and one in Slack, so this is my attempt at unifying those.
[Watch Video](https://vimeo.com/582254546/45e5945d91)
