### ISSUE TITLE
Add explicit code examples for Event Handling

### ISSUE THREAD

**Issue by ConorOkus** [lightningdevkit/lightningdevkit.org#74]
We currently make it clear that multiple types of events need to be handled, but the user has to do some external digging to the site to find examples of how to do this [here](https://github.com/lightningdevkit/ldk-sample/blob/bc07db6ca4a3323d8718a27f85182b8157a20750/src/main.rs#L101-L240).

In general, I think we should break up our guides/tutorials into separate pages to allow more room to add these code examples directly into the docs e.g `Initialize the ChannelManagerPersister` would have its own page with example code for each type of event handling.

**Comment by jkczyz** [comment]
Also see #33 and comments on #27. Currently, some event handling is covered in ["Using LDK"](https://github.com/lightningdevkit/lightningdevkit.org/blob/main/docs/using_ldk.md).
