### ISSUE TITLE
TxFilter shouldn't be visually shown in app code

### ISSUE THREAD

**Issue by moneyball** [lightningdevkit/lightningdevkit.org#78]
My understanding is that TxFilter is in the LDK not the app code. We should have @jkczyz or someone confirm and update the visual.

https://ldk-docs-preview.netlify.app/architecture/

**Comment by TheBlueMatt** [comment]
`TxFilter` is an interface that the user has to provide if they want to provide filtered/non-full blocks, and then they use that to receive information about which transactions they need to watch the chain for.

**Comment by jkczyz** [comment]
Yeah, it corresponds to a user-defined implementation of `chain::Filter`. Hopefully, the following docs make the purpose clear but happy to update if not:

https://docs.rs/lightning/0.0.100/lightning/chain/trait.Filter.html
