### ISSUE TITLE
Syntax highlighting is unreadable within "Tip" blocks when viewed in light mode

### ISSUE THREAD

**Issue by sbddesign** [lightningdevkit/lightningdevkit.org#91]
The syntax highlighting of `<code>` elements within a `div.custom-block tip` has white text with a light background, and can't be read without manually highlighting with the mouse cursor. I suggest a darker color for syntax highlights when they are contained in a tip block in light mode. Replicated in Brave and Firefox on macOS.

![Screen Shot 2021-10-29 at 10 52 07 AM](https://user-images.githubusercontent.com/2414177/139456911-f7342fac-0be3-4b78-9c9a-334b99dea3f5.png)

**Comment by dennisreimann** [comment]
Fixed, I was using the wrong background color, not the light one Christoph proposed.
